services:
    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example_root_password
            MYSQL_DATABASE: example_db
            MYSQL_USER: example_user
            MYSQL_PASSWORD: example_password
        ports:
            - '3306:3306'
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: example_root_password
        ports:
            - '8080:80'
        depends_on:
            - db

volumes:
    db_data:
